Class cysnet.clinicaDental.msg.ConsulatCitaPorIdRequest Extends Ens.Request
{

/// Description
Property idCita As %Integer;

Storage Default
{
<Data name="ConsulatCitaPorIdRequestDefaultData">
<Subscript>"ConsulatCitaPorIdRequest"</Subscript>
<Value name="1">
<Value>idCita</Value>
</Value>
</Data>
<DefaultData>ConsulatCitaPorIdRequestDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
